package com.sgq.pojo;

import java.util.Date;

public class UserWantCollection {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userwantcollection.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userwantcollection.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userwantcollection.goods_id
     *
     * @mbggenerated
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userwantcollection.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userwantcollection.is_support
     *
     * @mbggenerated
     */
    private Integer isSupport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userwantcollection.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userwantcollection.is_love
     *
     * @mbggenerated
     */
    private Integer isLove;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userwantcollection.id
     *
     * @return the value of userwantcollection.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userwantcollection.id
     *
     * @param id the value for userwantcollection.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userwantcollection.uid
     *
     * @return the value of userwantcollection.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userwantcollection.uid
     *
     * @param uid the value for userwantcollection.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userwantcollection.goods_id
     *
     * @return the value of userwantcollection.goods_id
     *
     * @mbggenerated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userwantcollection.goods_id
     *
     * @param goodsId the value for userwantcollection.goods_id
     *
     * @mbggenerated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userwantcollection.create_time
     *
     * @return the value of userwantcollection.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userwantcollection.create_time
     *
     * @param createTime the value for userwantcollection.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userwantcollection.is_support
     *
     * @return the value of userwantcollection.is_support
     *
     * @mbggenerated
     */
    public Integer getIsSupport() {
        return isSupport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userwantcollection.is_support
     *
     * @param isSupport the value for userwantcollection.is_support
     *
     * @mbggenerated
     */
    public void setIsSupport(Integer isSupport) {
        this.isSupport = isSupport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userwantcollection.modify_time
     *
     * @return the value of userwantcollection.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userwantcollection.modify_time
     *
     * @param modifyTime the value for userwantcollection.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userwantcollection.is_love
     *
     * @return the value of userwantcollection.is_love
     *
     * @mbggenerated
     */
    public Integer getIsLove() {
        return isLove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userwantcollection.is_love
     *
     * @param isLove the value for userwantcollection.is_love
     *
     * @mbggenerated
     */
    public void setIsLove(Integer isLove) {
        this.isLove = isLove;
    }
}