package com.sgq.dao;

import com.sgq.pojo.UserWantCollection;

public interface UserWantCollectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userwantcollection
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userwantcollection
     *
     * @mbggenerated
     */
    int insert(UserWantCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userwantcollection
     *
     * @mbggenerated
     */
    int insertSelective(UserWantCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userwantcollection
     *
     * @mbggenerated
     */
    UserWantCollection selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userwantcollection
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserWantCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userwantcollection
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserWantCollection record);
}